version: '3'
services:
  btc:
    build: ./bitcoind
    image: cherijs/bitcoind:latest
    container_name: btc
    restart: unless-stopped
    ports:
      - 8333
    volumes:
      - ./bitcoind/bitcoin.conf:/root/.bitcoin/bitcoin.conf
      - bitcoind:/root/.bitcoin/ # data persistence

  lnd:
    build: ./lnd
    image: cherijs/lnd:latest
    container_name: lnd
    restart: unless-stopped
    volumes:
      - ./lnd/lnd.conf:/root/.lnd/lnd.conf
      - bitcoind:/root/.bitcoin/
      - lnd:/root/.lnd/ # data persistence
    command:
      --debuglevel=debug
      --maxpendingchannels=10
      --rpclisten=0.0.0.0:10009
      --color=#4126a7
      --alias=LND
      --bitcoin.active
      --bitcoin.testnet
      --bitcoin.node=bitcoind
      --bitcoind.rpchost=btc
      --bitcoind.rpcuser=test
      --bitcoind.rpcpass=test
      --bitcoind.zmqpubrawblock=tcp://btc:28332
      --bitcoind.zmqpubrawtx=tcp://btc:28333
#      --externalip=88.135.143.213
#      --tlsextraip=88.135.143.213
#      --adminmacaroonpath=/root/.lnd/admin.macaroon
#      --readonlymacaroonpath=/root/.lnd/readonly.macaroon
#      --invoicemacaroonpath=/root/.lnd/invoice.macaroon
#      --autopilot.active
#      --autopilot.maxchannels=5
#      --autopilot.allocation=0.6

  channelbackup:
    build: ./channelbackup
    container_name: channelbackup
    restart: unless-stopped
    volumes:
      - lnd:/root/.lnd/ # data persistence

volumes:
  bitcoind:
  lnd:
